---
# file: roles/swarm/tasks/main.yml

- name: Setup swarm into first manager
  shell: docker swarm init --advertise-addr {{ ansible_eth0['ipv4']['address'] }}
  when: "{{ docker_info.stdout.find('Swarm: inactive') != -1 }}"

- name: Get docker swarm token manager
  shell: docker swarm join-token -q manager
  register: manager_token

- name: Get docker swarm token worker
  shell: docker swarm join-token -q worker
  register: worker_token
