---
# file: roles/managers/tasks/main.yml

- name: Join managers
  shell: "docker swarm join --token {{ hostvars['manager1']['manager_token']['stdout'] }} {{ hostvars['manager1']['ansible_eth0']['ipv4']['address'] }}:2377"
  when: "{{ docker_info.stdout.find('Swarm: inactive') != -1 }}"
  retries: 3
  delay: 20
