---
# file: roles/install/tasks/install_centos.yml

- name: Install docker dependencies
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add docker repository
  yum_repository:
    name: docker
    description: Docker repository
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker-ce
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Enable service and start docker
  systemd:
    name: docker
    enabled: yes
    state: started
